In [31]:
import pymysql

# MySQL 연결 설정
def connect_to_db():
    return pymysql.connect(
        host="192.168.56.101",  # MySQL 서버 IP
        user="yoonseongahn",   # MySQL 사용자 이름
        password="1234",       # MySQL 사용자 비밀번호
        database="madang",     # 데이터베이스 이름
        port=4567,             # MySQL 포트
        charset="utf8mb4",
        cursorclass=pymysql.cursors.DictCursor,
    )

# 공통: 출력 플러시
import sys
def flush_output():
    sys.stdout.flush()

# 1. 책(Book) 관련 기능
def insert_book(bookid, bookname, publisher, price):
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = "INSERT INTO Book (bookid, bookname, publisher, price) VALUES (%s, %s, %s, %s)"
            cursor.execute(sql, (bookid, bookname, publisher, price))
        conn.commit()
        print(f"Book '{bookname}' inserted successfully!")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

def delete_book(bookid):
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = "DELETE FROM Book WHERE bookid = %s"
            cursor.execute(sql, (bookid,))
        conn.commit()
        if cursor.rowcount > 0:
            print(f"Book with ID {bookid} deleted successfully!")
        else:
            print(f"No book found with ID {bookid}.")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

def search_book_by_name(bookname):
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = "SELECT * FROM Book WHERE bookname LIKE %s"
            cursor.execute(sql, ('%' + bookname + '%',))
            results = cursor.fetchall()
            print("Search results for books:")
            for book in results:
                print(f"ID: {book['bookid']}, Name: {book['bookname']}, Publisher: {book['publisher']}, Price: {book['price']}")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

def view_all_books():
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = "SELECT * FROM Book"
            cursor.execute(sql)
            results = cursor.fetchall()
            print("Books in database:")
            for book in results:
                print(f"ID: {book['bookid']}, Name: {book['bookname']}, Publisher: {book['publisher']}, Price: {book['price']}")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

# 2. 고객(Customer) 관련 기능
def insert_customer(custid, name, address, phone):
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = "INSERT INTO Customer (custid, name, address, phone) VALUES (%s, %s, %s, %s)"
            cursor.execute(sql, (custid, name, address, phone))
        conn.commit()
        print(f"Customer '{name}' inserted successfully!")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

def delete_customer(custid):
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = "DELETE FROM Customer WHERE custid = %s"
            cursor.execute(sql, (custid,))
        conn.commit()
        if cursor.rowcount > 0:
            print(f"Customer with ID {custid} deleted successfully!")
        else:
            print(f"No customer found with ID {custid}.")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

def search_customer_by_name(name):
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = "SELECT * FROM Customer WHERE name LIKE %s"
            cursor.execute(sql, ('%' + name + '%',))
            results = cursor.fetchall()
            print("Search results for customers:")
            for customer in results:
                print(f"ID: {customer['custid']}, Name: {customer['name']}, Address: {customer['address']}, Phone: {customer['phone']}")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

def view_all_customers():
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = "SELECT * FROM Customer"
            cursor.execute(sql)
            results = cursor.fetchall()
            print("Customers in database:")
            for customer in results:
                print(f"ID: {customer['custid']}, Name: {customer['name']}, Address: {customer['address']}, Phone: {customer['phone']}")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

# 3. 주문(Orders) 관련 기능
def insert_order(orderid, custid, bookid, saleprice, orderdate):
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = "INSERT INTO Orders (orderid, custid, bookid, saleprice, orderdate) VALUES (%s, %s, %s, %s, %s)"
            cursor.execute(sql, (orderid, custid, bookid, saleprice, orderdate))
        conn.commit()
        print(f"Order with ID {orderid} inserted successfully!")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

def delete_order_by_id_and_book(orderid, bookname):
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = """
            DELETE Orders
            FROM Orders
            JOIN Book ON Orders.bookid = Book.bookid
            WHERE Orders.orderid = %s AND Book.bookname LIKE %s
            """
            cursor.execute(sql, (orderid, '%' + bookname + '%'))
        conn.commit()
        if cursor.rowcount > 0:
            print(f"Order with ID {orderid} and book '{bookname}' deleted successfully!")
        else:
            print(f"No order found with ID {orderid} and book name '{bookname}'.")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

def search_order_by_custid(custid):
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = """
            SELECT Orders.orderid, Customer.name AS customer_name, Book.bookname AS book_name, Orders.saleprice, Orders.orderdate
            FROM Orders
            JOIN Customer ON Orders.custid = Customer.custid
            JOIN Book ON Orders.bookid = Book.bookid
            WHERE Orders.custid = %s
            """
            cursor.execute(sql, (custid,))
            results = cursor.fetchall()
            if results:
                print(f"Orders for customer ID {custid}:")
                for order in results:
                    print(f"Order ID: {order['orderid']}, Customer: {order['customer_name']}, Book: {order['book_name']}, Sale Price: {order['saleprice']}, Order Date: {order['orderdate']}")
            else:
                print(f"No orders found for customer ID {custid}.")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()



def view_all_orders():
    conn = connect_to_db()
    try:
        with conn.cursor() as cursor:
            sql = """
            SELECT Orders.orderid, Customer.name AS customer_name, Book.bookname AS book_name, Orders.saleprice, Orders.orderdate
            FROM Orders
            JOIN Customer ON Orders.custid = Customer.custid
            JOIN Book ON Orders.bookid = Book.bookid
            """
            cursor.execute(sql)
            results = cursor.fetchall()
            print("Orders in database:")
            for order in results:
                print(f"Order ID: {order['orderid']}, Customer: {order['customer_name']}, Book: {order['book_name']}, Sale Price: {order['saleprice']}, Order Date: {order['orderdate']}")
    except Exception as e:
        print("Error:", e)
    finally:
        conn.close()

In [39]:
if __name__ == "__main__":
    print("Welcome to the Madang Database Management System!")
    while True:
        try:
            print("\nOptions:")
            print("1. Insert a new book")
            print("2. Delete a book by ID")
            print("3. Search for a book by name")
            print("4. View all books")
            print("5. Insert a new customer")
            print("6. Delete a customer by ID")
            print("7. Search for a customer by name")
            print("8. View all customers")
            print("9. Insert a new order")
            print("10. Delete an order by ID and book name")
            print("11. Search for orders by customer ID")
            print("12. View all orders")
            print("13. Exit")

            choice = input("Enter your choice: ")

            if choice == "1":
                # Insert a new book
                bookid = int(input("Enter book ID: "))
                bookname = input("Enter book name: ")
                publisher = input("Enter publisher name: ")
                price = int(input("Enter book price: "))
                insert_book(bookid, bookname, publisher, price)

            elif choice == "2":
                # Delete a book by ID
                bookid = int(input("Enter book ID to delete: "))
                delete_book(bookid)

            elif choice == "3":
                # Search for a book by name
                bookname = input("Enter book name to search: ")
                search_book_by_name(bookname)

            elif choice == "4":
                # View all books
                view_all_books()

            elif choice == "5":
                # Insert a new customer
                custid = int(input("Enter customer ID: "))
                name = input("Enter customer name: ")
                address = input("Enter customer address: ")
                phone = input("Enter customer phone (or leave blank for NULL): ")
                phone = None if phone.strip() == "" else phone
                insert_customer(custid, name, address, phone)

            elif choice == "6":
                # Delete a customer by ID
                custid = int(input("Enter customer ID to delete: "))
                delete_customer(custid)

            elif choice == "7":
                # Search for a customer by name
                name = input("Enter customer name to search: ")
                search_customer_by_name(name)

            elif choice == "8":
                # View all customers
                view_all_customers()

            elif choice == "9":
                # Insert a new order
                orderid = int(input("Enter order ID: "))
                custid = int(input("Enter customer ID: "))
                bookid = int(input("Enter book ID: "))
                saleprice = int(input("Enter sale price: "))
                orderdate = input("Enter order date (YYYY-MM-DD): ")
                insert_order(orderid, custid, bookid, saleprice, orderdate)

            elif choice == "10":
                # Delete an order by ID and book name
                orderid = int(input("Enter order ID to delete: "))
                bookname = input("Enter book name associated with the order: ")
                delete_order_by_id_and_book(orderid, bookname)

            elif choice == "11":
                # Search for orders by customer ID
                custid = int(input("Enter customer ID to search for orders: "))
                search_order_by_custid(custid)

            elif choice == "12":
                # View all orders
                view_all_orders()

            elif choice == "13":
                # Exit
                print("Goodbye!")
                break

            else:
                print("Invalid choice. Please try again.")
        except Exception as e:
            print("An error occurred:", e)

Welcome to the Madang Database Management System!

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Book '수리통계학' inserted successfully!

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Customer '안윤성' inserted successfully!

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Order with ID 11 inserted successfully!

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Books in database:
ID: 1, Name: 축구의 역사, Publisher: 굿스포츠, Price: 7000
ID: 2, Name: 축구아는 여자, Publisher: 나무수, Price: 13000
ID: 3, Name: 축구의 이해, Publisher: 대한미디어, Price: 22000
ID: 4, Name: 골프 바이블, Publisher: 대한미디어, Price: 35000
ID: 5, Name: 피겨 교본, Publisher: 굿스포츠, Price: 8000
ID: 6, Name: 역도 단계별기술, Publisher: 굿스포츠, Price: 6000
ID: 7, Name: 야구의 추억, Publisher: 이상미디어, Price: 20000
ID: 8, Name: 야구를 부탁해, Publisher: 이상미디어, Price: 13000
ID: 9, Name: 올림픽 이야기, Publisher: 삼성당, Price: 7500
ID: 10, Name: Olympic Champions, Publisher: Pearson, Price: 13000
ID: 11, Name: 수리통계학, Publisher: 나종화, Price: 25000
ID: 14, Name: 스포츠 의학, Publisher: Pearson, Price: None
ID: 21, Name: Zen Golf, Publisher: Pearson, Price: 12000
ID: 22, Name: Soccer Skills, Publisher: Human Kinetics, Price: 15000

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Customers in database:
ID: 1, Name: 박지성, Address: 영국 맨체스타, Phone: 000-5000-0001
ID: 2, Name: 김연아, Address: 대한민국 서울, Phone: 000-6000-0001
ID: 3, Name: 장미란, Address: 대한민국 강원도, Phone: 000-7000-0001
ID: 4, Name: 추신수, Address: 미국 클리블랜드, Phone: 000-8000-0001
ID: 5, Name: 박세리, Address: 대한민국 부산, Phone: None
ID: 6, Name: 안윤성, Address: 충청북도 청주시, Phone: 01096683692

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Orders in database:
Order ID: 1, Customer: 박지성, Book: 축구의 역사, Sale Price: 6000, Order Date: 2014-07-01
Order ID: 2, Customer: 박지성, Book: 축구의 이해, Sale Price: 21000, Order Date: 2014-07-03
Order ID: 3, Customer: 김연아, Book: 피겨 교본, Sale Price: 8000, Order Date: 2014-07-03
Order ID: 4, Customer: 장미란, Book: 역도 단계별기술, Sale Price: 6000, Order Date: 2014-07-04
Order ID: 5, Customer: 추신수, Book: 야구의 추억, Sale Price: 20000, Order Date: 2014-07-05
Order ID: 6, Customer: 박지성, Book: 축구아는 여자, Sale Price: 12000, Order Date: 2014-07-07
Order ID: 7, Customer: 추신수, Book: 야구를 부탁해, Sale Price: 13000, Order Date: 2014-07-07
Order ID: 8, Customer: 장미란, Book: Olympic Champions, Sale Price: 12000, Order Date: 2014-07-08
Order ID: 9, Customer: 김연아, Book: Olympic Champions, Sale Price: 7000, Order Date: 2014-07-09
Order ID: 10, Customer: 장미란, Book: 야구를 부탁해, Sale Price: 13000, Order Date: 2014-07-10
Order ID: 11, Customer: 안윤성, Book: 수리통계학, Sale Price: 25000, Order Date: 2024-11-16

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Search results for books:
ID: 11, Name: 수리통계학, Publisher: 나종화, Price: 25000

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Search results for customers:
ID: 6, Name: 안윤성, Address: 충청북도 청주시, Phone: 01096683692

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Orders for customer ID 6:
Order ID: 11, Customer: 안윤성, Book: 수리통계학, Sale Price: 25000, Order Date: 2024-11-16

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Error: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`madang`.`Orders`, CONSTRAINT `Orders_ibfk_2` FOREIGN KEY (`bookid`) REFERENCES `Book` (`bookid`))')

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Error: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`madang`.`Orders`, CONSTRAINT `Orders_ibfk_1` FOREIGN KEY (`custid`) REFERENCES `Customer` (`custid`))')

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Order with ID 11 and book '수리통계학' deleted successfully!

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Book with ID 11 deleted successfully!

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Customer with ID 6 deleted successfully!

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Books in database:
ID: 1, Name: 축구의 역사, Publisher: 굿스포츠, Price: 7000
ID: 2, Name: 축구아는 여자, Publisher: 나무수, Price: 13000
ID: 3, Name: 축구의 이해, Publisher: 대한미디어, Price: 22000
ID: 4, Name: 골프 바이블, Publisher: 대한미디어, Price: 35000
ID: 5, Name: 피겨 교본, Publisher: 굿스포츠, Price: 8000
ID: 6, Name: 역도 단계별기술, Publisher: 굿스포츠, Price: 6000
ID: 7, Name: 야구의 추억, Publisher: 이상미디어, Price: 20000
ID: 8, Name: 야구를 부탁해, Publisher: 이상미디어, Price: 13000
ID: 9, Name: 올림픽 이야기, Publisher: 삼성당, Price: 7500
ID: 10, Name: Olympic Champions, Publisher: Pearson, Price: 13000
ID: 14, Name: 스포츠 의학, Publisher: Pearson, Price: None
ID: 21, Name: Zen Golf, Publisher: Pearson, Price: 12000
ID: 22, Name: Soccer Skills, Publisher: Human Kinetics, Price: 15000

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Customers in database:
ID: 1, Name: 박지성, Address: 영국 맨체스타, Phone: 000-5000-0001
ID: 2, Name: 김연아, Address: 대한민국 서울, Phone: 000-6000-0001
ID: 3, Name: 장미란, Address: 대한민국 강원도, Phone: 000-7000-0001
ID: 4, Name: 추신수, Address: 미국 클리블랜드, Phone: 000-8000-0001
ID: 5, Name: 박세리, Address: 대한민국 부산, Phone: None

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Orders in database:
Order ID: 1, Customer: 박지성, Book: 축구의 역사, Sale Price: 6000, Order Date: 2014-07-01
Order ID: 2, Customer: 박지성, Book: 축구의 이해, Sale Price: 21000, Order Date: 2014-07-03
Order ID: 3, Customer: 김연아, Book: 피겨 교본, Sale Price: 8000, Order Date: 2014-07-03
Order ID: 4, Customer: 장미란, Book: 역도 단계별기술, Sale Price: 6000, Order Date: 2014-07-04
Order ID: 5, Customer: 추신수, Book: 야구의 추억, Sale Price: 20000, Order Date: 2014-07-05
Order ID: 6, Customer: 박지성, Book: 축구아는 여자, Sale Price: 12000, Order Date: 2014-07-07
Order ID: 7, Customer: 추신수, Book: 야구를 부탁해, Sale Price: 13000, Order Date: 2014-07-07
Order ID: 8, Customer: 장미란, Book: Olympic Champions, Sale Price: 12000, Order Date: 2014-07-08
Order ID: 9, Customer: 김연아, Book: Olympic Champions, Sale Price: 7000, Order Date: 2014-07-09
Order ID: 10, Customer: 장미란, Book: 야구를 부탁해, Sale Price: 13000, Order Date: 2014-07-10

Options:
1. Insert a new book
2. Delete a book by ID
3. Search for a book by name
4. View all books
5. Insert a new customer
6. Delete a customer by ID
7. Search for a customer by name
8. View all customers
9. Insert a new order
10. Delete an order by ID and book name
11. Search for orders by customer ID
12. View all orders
13. Exit
Goodbye!